const newDate = new Date();
export const fakeData = [
  {
    keyIndex: 'Học Tập',
    data: [
      {
        id: 1,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 2,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 3,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 4,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 5,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 6,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 7,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
    ],
  },
  {
    keyIndex: 'Hoạt động',
    data: [
      {
        id: 1,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 2,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 3,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 4,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 5,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 6,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 7,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
    ],
  },
  {
    keyIndex: 'Học phí',
    data: [
      {
        id: 1,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 2,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 3,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 4,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
    ],
  },
  {
    keyIndex: 'Lịch học',
    data: [
      {
        id: 632204,
        day: '21/03/2022 00:00',
        room_name: 'P401',
        area_name: 'TVB',
        subject_code: 'VIE103',
        subject_name: 'Giáo dục thể chất - Vovinam 1',
        group_id: 31167,
        group_name: 'VIE103.02',
        activity_leader_login: 'thaottt',
        slot: 2,
        slot_time: 'Ca 2 (21/03/2022 09:25 - 21/03/2022 11:25)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '* Các thế khóa gỡ trình độ 1: Túm tóc trước tay phải và tay trái\r\n* Thể lực chung',
      },
      {
        id: 627232,
        day: '21/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (21/03/2022 12:00 - 21/03/2022 14:00)',
        url_room_online: 'https://meet.google.com/feu-nswx-wos?pli=1&authuser=1',
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 4.1: Xử lý đầu vào với Form & Event (P1)\r\nLab4(P1)',
      },
      {
        id: 614613,
        day: '21/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (21/03/2022 18:30 - 21/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành + Kiểm tra',
        syllabus_plan_noi_dung:
          '"\r\nBài 6: Tổ chức và quản lý\r\n- Các loại hình doanh nghiệp\r\n- Trách nhiệm pháp lý và bảo hiểm\r\nTest 1"\r\n',
      },
      {
        id: 645952,
        day: '22/03/2022 00:00',
        room_name: 'F101',
        area_name: 'TVB',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 5,
        slot_time: 'Ca 5 (22/03/2022 16:20 - 22/03/2022 18:20)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung: 'Communication skills practice 8',
      },
      {
        id: 632205,
        day: '23/03/2022 00:00',
        room_name: 'P401',
        area_name: 'TVB',
        subject_code: 'VIE103',
        subject_name: 'Giáo dục thể chất - Vovinam 1',
        group_id: 31167,
        group_name: 'VIE103.02',
        activity_leader_login: 'thaottt',
        slot: 2,
        slot_time: 'Ca 2 (23/03/2022 09:25 - 23/03/2022 11:25)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '* Các thế khóa gỡ trình độ 1: Túm tóc sau tay phải và tay trái\r\n* Thể lực chung',
      },
      {
        id: 627233,
        day: '23/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (23/03/2022 12:00 - 23/03/2022 14:00)',
        url_room_online: null,
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 4.2: API request với React (P2)\r\nLab4(P2), Quiz4\r\nNộp bài Assignment giai đoạn 1',
      },
      {
        id: 614614,
        day: '23/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (23/03/2022 18:30 - 23/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung: 'Đánh giá giai đoạn 1 của bản KHKD\r\n',
      },
      {
        id: 645953,
        day: '24/03/2022 00:00',
        room_name: 'Google Meet 1',
        area_name: 'Google Meet',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 10,
        slot_time: 'Ca 10 (24/03/2022 00:00 - 24/03/2022 23:59)',
        url_room_online: null,
        syllabus_plan_description: 'Giờ học online',
        syllabus_plan_noi_dung:
          '"Bài online 10: Discuss ways to improve appearance\r\n- Kĩ năng đọc: diễn giải theo cách khác (paraphrase), đọc hiểu ngữ cảnh (understand from context)\r\n- Kĩ năng nghe để ghi lại thông tin chính (note-taking)"',
      },
      {
        id: 627234,
        day: '25/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (25/03/2022 12:00 - 25/03/2022 14:00)',
        url_room_online: null,
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 5.1: Redux(P1)\r\n- Redux\r\n- React với Redux\r\nLab5(P1)',
      },
      {
        id: 614615,
        day: '25/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (25/03/2022 18:30 - 25/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '"Bài 7: Mua hàng cho doanh nghiệp và kinh doanh xanh\r\n- Mua thiết bị\r\n- Mua nguyên liệu thô\r\n- Mua hàng thành phẩm\r\n- Doanh nghiệp của bạn và tài nguyên thiên nhiên\r\n- Tăng hiệu quả và lợi nhuận: giảm thiểu, tái sử dụng, tái chế"\r\n',
      },
      {
        id: 645954,
        day: '26/03/2022 00:00',
        room_name: 'F101',
        area_name: 'TVB',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 8,
        slot_time: 'Ca 8 (26/03/2022 20:30 - 26/03/2022 22:30)',
        url_room_online: null,
        syllabus_plan_description: 'Remote2',
        syllabus_plan_noi_dung: 'Ôn tập',
      },
    ]
  },
  {
    keyIndex: 'Lịch thi',
    data: [
      {
        id: 632204,
        day: '21/03/2022 00:00',
        room_name: 'P401',
        area_name: 'TVB',
        subject_code: 'VIE103',
        subject_name: 'Giáo dục thể chất - Vovinam 1',
        group_id: 31167,
        group_name: 'VIE103.02',
        activity_leader_login: 'thaottt',
        slot: 2,
        slot_time: 'Ca 2 (21/03/2022 09:25 - 21/03/2022 11:25)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '* Các thế khóa gỡ trình độ 1: Túm tóc trước tay phải và tay trái\r\n* Thể lực chung',
      },
      {
        id: 627232,
        day: '21/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (21/03/2022 12:00 - 21/03/2022 14:00)',
        url_room_online: 'https://meet.google.com/feu-nswx-wos?pli=1&authuser=1',
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 4.1: Xử lý đầu vào với Form & Event (P1)\r\nLab4(P1)',
      },
      {
        id: 614613,
        day: '21/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (21/03/2022 18:30 - 21/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành + Kiểm tra',
        syllabus_plan_noi_dung:
          '"\r\nBài 6: Tổ chức và quản lý\r\n- Các loại hình doanh nghiệp\r\n- Trách nhiệm pháp lý và bảo hiểm\r\nTest 1"\r\n',
      },
      {
        id: 645952,
        day: '22/03/2022 00:00',
        room_name: 'F101',
        area_name: 'TVB',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 5,
        slot_time: 'Ca 5 (22/03/2022 16:20 - 22/03/2022 18:20)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung: 'Communication skills practice 8',
      },
      {
        id: 632205,
        day: '23/03/2022 00:00',
        room_name: 'P401',
        area_name: 'TVB',
        subject_code: 'VIE103',
        subject_name: 'Giáo dục thể chất - Vovinam 1',
        group_id: 31167,
        group_name: 'VIE103.02',
        activity_leader_login: 'thaottt',
        slot: 2,
        slot_time: 'Ca 2 (23/03/2022 09:25 - 23/03/2022 11:25)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '* Các thế khóa gỡ trình độ 1: Túm tóc sau tay phải và tay trái\r\n* Thể lực chung',
      },
      {
        id: 627233,
        day: '23/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (23/03/2022 12:00 - 23/03/2022 14:00)',
        url_room_online: null,
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 4.2: API request với React (P2)\r\nLab4(P2), Quiz4\r\nNộp bài Assignment giai đoạn 1',
      },
      {
        id: 614614,
        day: '23/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (23/03/2022 18:30 - 23/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung: 'Đánh giá giai đoạn 1 của bản KHKD\r\n',
      },
      {
        id: 645953,
        day: '24/03/2022 00:00',
        room_name: 'Google Meet 1',
        area_name: 'Google Meet',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 10,
        slot_time: 'Ca 10 (24/03/2022 00:00 - 24/03/2022 23:59)',
        url_room_online: null,
        syllabus_plan_description: 'Giờ học online',
        syllabus_plan_noi_dung:
          '"Bài online 10: Discuss ways to improve appearance\r\n- Kĩ năng đọc: diễn giải theo cách khác (paraphrase), đọc hiểu ngữ cảnh (understand from context)\r\n- Kĩ năng nghe để ghi lại thông tin chính (note-taking)"',
      },
      {
        id: 627234,
        day: '25/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (25/03/2022 12:00 - 25/03/2022 14:00)',
        url_room_online: null,
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 5.1: Redux(P1)\r\n- Redux\r\n- React với Redux\r\nLab5(P1)',
      },
      {
        id: 614615,
        day: '25/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (25/03/2022 18:30 - 25/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '"Bài 7: Mua hàng cho doanh nghiệp và kinh doanh xanh\r\n- Mua thiết bị\r\n- Mua nguyên liệu thô\r\n- Mua hàng thành phẩm\r\n- Doanh nghiệp của bạn và tài nguyên thiên nhiên\r\n- Tăng hiệu quả và lợi nhuận: giảm thiểu, tái sử dụng, tái chế"\r\n',
      },
      {
        id: 645954,
        day: '26/03/2022 00:00',
        room_name: 'F101',
        area_name: 'TVB',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 8,
        slot_time: 'Ca 8 (26/03/2022 20:30 - 26/03/2022 22:30)',
        url_room_online: null,
        syllabus_plan_description: 'Remote2',
        syllabus_plan_noi_dung: 'Ôn tập',
      },
    ]
  },
  {
    keyIndex: 'Điểm danh',
    data: [
      {
        id: 1,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 2,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 3,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 4,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
    ],
  },
];

export const dataAttendance = [
  {
    member_login: 'dungtmph12934',
    group_id: 29729,
    group_name: 'GD16201',
    subject_code: 'SKI2015',
    skill_code: 'SKI201',
    subject_name: 'Kỹ năng làm việc',
    subject_id: 491,
    start_date: '04/01/2022',
    total_session: 16,
    total_to_now: 16,
    total_absent: 1,
    activities: [
      {
        id: 605340,
        groupid: '29729',
        course_slot: 1,
        day: '04/01/2022 - Tuesday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8117758,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605341,
        groupid: '29729',
        course_slot: 2,
        day: '06/01/2022 - Thursday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8141498,
        val: 0,
        val_text: 'Absent',
      },
      {
        id: 605342,
        groupid: '29729',
        course_slot: 3,
        day: '08/01/2022 - Saturday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8165055,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605343,
        groupid: '29729',
        course_slot: 4,
        day: '11/01/2022 - Tuesday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8193372,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605344,
        groupid: '29729',
        course_slot: 5,
        day: '13/01/2022 - Thursday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8222021,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605345,
        groupid: '29729',
        course_slot: 6,
        day: '15/01/2022 - Saturday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8251500,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605346,
        groupid: '29729',
        course_slot: 7,
        day: '18/01/2022 - Tuesday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8280352,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605347,
        groupid: '29729',
        course_slot: 8,
        day: '20/01/2022 - Thursday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8309256,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605348,
        groupid: '29729',
        course_slot: 9,
        day: '22/01/2022 - Saturday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8338529,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605349,
        groupid: '29729',
        course_slot: 10,
        day: '08/02/2022 - Tuesday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8368061,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605350,
        groupid: '29729',
        course_slot: 11,
        day: '10/02/2022 - Thursday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8398336,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605351,
        groupid: '29729',
        course_slot: 12,
        day: '12/02/2022 - Saturday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8425892,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605352,
        groupid: '29729',
        course_slot: 13,
        day: '15/02/2022 - Tuesday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8456005,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605353,
        groupid: '29729',
        course_slot: 14,
        day: '17/02/2022 - Thursday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8485907,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605354,
        groupid: '29729',
        course_slot: 15,
        day: '19/02/2022 - Saturday',
        slot: 3,
        leader_login: 'thuynt',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8515062,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605355,
        groupid: '29729',
        course_slot: 16,
        day: '22/02/2022 - Tuesday',
        slot: 3,
        leader_login: 'huongpt55',
        description: 'Lý thuyết',
        done: 1,
        note: '',
        attendance_id: 8545887,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 605356,
        groupid: '29729',
        course_slot: 300,
        day: '26/02/2022 - Saturday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 605357,
        groupid: '29729',
        course_slot: 301,
        day: '01/03/2022 - Tuesday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 605358,
        groupid: '29729',
        course_slot: 302,
        day: '03/03/2022 - Thursday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
    ],
  },
  {
    member_login: 'dungtmph12934',
    group_id: 30276,
    group_name: 'HM16201',
    subject_code: 'SYB3011',
    skill_code: 'SYB301',
    subject_name: 'Khởi sự doanh nghiệp',
    subject_id: 794,
    start_date: '07/03/2022',
    total_session: 17,
    total_to_now: 6,
    total_absent: 1,
    activities: [
      {
        id: 614607,
        groupid: '30276',
        course_slot: 1,
        day: '07/03/2022 - Monday',
        slot: 6,
        leader_login: 'hangptt35',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8605406,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 614608,
        groupid: '30276',
        course_slot: 2,
        day: '09/03/2022 - Wednesday',
        slot: 6,
        leader_login: 'hangptt35',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8635183,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 614609,
        groupid: '30276',
        course_slot: 3,
        day: '11/03/2022 - Friday',
        slot: 6,
        leader_login: 'hangptt35',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8664221,
        val: 0,
        val_text: 'Absent',
      },
      {
        id: 614610,
        groupid: '30276',
        course_slot: 4,
        day: '14/03/2022 - Monday',
        slot: 6,
        leader_login: 'hangptt35',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8695209,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 614611,
        groupid: '30276',
        course_slot: 5,
        day: '16/03/2022 - Wednesday',
        slot: 6,
        leader_login: 'hangptt35',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8726305,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 614612,
        groupid: '30276',
        course_slot: 6,
        day: '18/03/2022 - Friday',
        slot: 6,
        leader_login: 'hangptt35',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8758277,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 614613,
        groupid: '30276',
        course_slot: 7,
        day: '21/03/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành + Kiểm tra',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614614,
        groupid: '30276',
        course_slot: 8,
        day: '23/03/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614615,
        groupid: '30276',
        course_slot: 9,
        day: '25/03/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614616,
        groupid: '30276',
        course_slot: 10,
        day: '28/03/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614617,
        groupid: '30276',
        course_slot: 11,
        day: '30/03/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614618,
        groupid: '30276',
        course_slot: 12,
        day: '01/04/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614619,
        groupid: '30276',
        course_slot: 13,
        day: '04/04/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614620,
        groupid: '30276',
        course_slot: 14,
        day: '06/04/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614621,
        groupid: '30276',
        course_slot: 15,
        day: '08/04/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614622,
        groupid: '30276',
        course_slot: 16,
        day: '13/04/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành + Kiểm tra',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614623,
        groupid: '30276',
        course_slot: 17,
        day: '15/04/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614624,
        groupid: '30276',
        course_slot: 300,
        day: '20/04/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614625,
        groupid: '30276',
        course_slot: 301,
        day: '22/04/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 614626,
        groupid: '30276',
        course_slot: 302,
        day: '25/04/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
    ],
  },
  {
    member_login: 'dungtmph12934',
    group_id: 30765,
    group_name: 'WE16202',
    subject_code: 'WEB208',
    skill_code: 'WEB208',
    subject_name: 'Lập trình Front-End Framework 1',
    subject_id: 728,
    start_date: '07/01/2022',
    total_session: 17,
    total_to_now: 17,
    total_absent: 1,
    activities: [
      {
        id: 624197,
        groupid: '30765',
        course_slot: 1,
        day: '24/02/2022 - Thursday',
        slot: 6,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8573306,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624198,
        groupid: '30765',
        course_slot: 2,
        day: '07/01/2022 - Friday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8148800,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624199,
        groupid: '30765',
        course_slot: 3,
        day: '10/01/2022 - Monday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8172288,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624200,
        groupid: '30765',
        course_slot: 4,
        day: '12/01/2022 - Wednesday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8201443,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624201,
        groupid: '30765',
        course_slot: 5,
        day: '14/01/2022 - Friday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8230670,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624202,
        groupid: '30765',
        course_slot: 6,
        day: '17/01/2022 - Monday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8262831,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624203,
        groupid: '30765',
        course_slot: 7,
        day: '19/01/2022 - Wednesday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8289019,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624204,
        groupid: '30765',
        course_slot: 8,
        day: '21/01/2022 - Friday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8318170,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624205,
        groupid: '30765',
        course_slot: 9,
        day: '07/02/2022 - Monday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8347584,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624206,
        groupid: '30765',
        course_slot: 10,
        day: '09/02/2022 - Wednesday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8376610,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624207,
        groupid: '30765',
        course_slot: 11,
        day: '11/02/2022 - Friday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8406316,
        val: 0,
        val_text: 'Absent',
      },
      {
        id: 624208,
        groupid: '30765',
        course_slot: 12,
        day: '14/02/2022 - Monday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8437379,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624209,
        groupid: '30765',
        course_slot: 13,
        day: '16/02/2022 - Wednesday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8465305,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624210,
        groupid: '30765',
        course_slot: 14,
        day: '18/02/2022 - Friday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8494971,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624211,
        groupid: '30765',
        course_slot: 15,
        day: '21/02/2022 - Monday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8526633,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624212,
        groupid: '30765',
        course_slot: 16,
        day: '23/02/2022 - Wednesday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8552124,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624213,
        groupid: '30765',
        course_slot: 17,
        day: '25/02/2022 - Friday',
        slot: 1,
        leader_login: 'thienth',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8575327,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 624214,
        groupid: '30765',
        course_slot: 300,
        day: '02/03/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
    ],
  },
  {
    member_login: 'dungtmph12934',
    group_id: 30928,
    group_name: 'WE16202',
    subject_code: 'WEB209',
    skill_code: 'WEB209',
    subject_name: 'Lập trình Front-End Framework 2',
    subject_id: 729,
    start_date: '07/03/2022',
    total_session: 17,
    total_to_now: 6,
    total_absent: 0,
    activities: [
      {
        id: 627226,
        groupid: '30928',
        course_slot: 1,
        day: '07/03/2022 - Monday',
        slot: 3,
        leader_login: 'datlt34',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8597622,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 627227,
        groupid: '30928',
        course_slot: 2,
        day: '09/03/2022 - Wednesday',
        slot: 3,
        leader_login: 'datlt34',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8627685,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 627228,
        groupid: '30928',
        course_slot: 3,
        day: '11/03/2022 - Friday',
        slot: 3,
        leader_login: 'datlt34',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8657950,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 627229,
        groupid: '30928',
        course_slot: 4,
        day: '14/03/2022 - Monday',
        slot: 3,
        leader_login: 'datlt34',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8686800,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 627230,
        groupid: '30928',
        course_slot: 5,
        day: '16/03/2022 - Wednesday',
        slot: 3,
        leader_login: 'datlt34',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8720397,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 627231,
        groupid: '30928',
        course_slot: 6,
        day: '18/03/2022 - Friday',
        slot: 3,
        leader_login: 'datlt34',
        description: 'Tích hợp(LT+TH)',
        done: 1,
        note: '',
        attendance_id: 8752367,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 627232,
        groupid: '30928',
        course_slot: 7,
        day: '21/03/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627233,
        groupid: '30928',
        course_slot: 8,
        day: '23/03/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627234,
        groupid: '30928',
        course_slot: 9,
        day: '25/03/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627235,
        groupid: '30928',
        course_slot: 10,
        day: '28/03/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627236,
        groupid: '30928',
        course_slot: 11,
        day: '30/03/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627237,
        groupid: '30928',
        course_slot: 12,
        day: '01/04/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627238,
        groupid: '30928',
        course_slot: 13,
        day: '04/04/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627239,
        groupid: '30928',
        course_slot: 14,
        day: '06/04/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627240,
        groupid: '30928',
        course_slot: 15,
        day: '08/04/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627241,
        groupid: '30928',
        course_slot: 16,
        day: '13/04/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Tích hợp(LT+TH)',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627242,
        groupid: '30928',
        course_slot: 17,
        day: '15/04/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627243,
        groupid: '30928',
        course_slot: 300,
        day: '20/04/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627244,
        groupid: '30928',
        course_slot: 301,
        day: '22/04/2022 - Friday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 627245,
        groupid: '30928',
        course_slot: 302,
        day: '25/04/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
    ],
  },
  {
    member_login: 'dungtmph12934',
    group_id: 31167,
    group_name: 'VIE103.02',
    subject_code: 'VIE103',
    skill_code: 'VIE103',
    subject_name: 'Giáo dục thể chất - Vovinam 1',
    subject_id: 95,
    start_date: '05/01/2022',
    total_session: 23,
    total_to_now: 15,
    total_absent: 3,
    activities: [
      {
        id: 632189,
        groupid: '31167',
        course_slot: 1,
        day: '05/01/2022 - Wednesday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8224022,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632190,
        groupid: '31167',
        course_slot: 2,
        day: '10/01/2022 - Monday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8175309,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632191,
        groupid: '31167',
        course_slot: 3,
        day: '12/01/2022 - Wednesday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8204462,
        val: 0,
        val_text: 'Absent',
      },
      {
        id: 632192,
        groupid: '31167',
        course_slot: 4,
        day: '17/01/2022 - Monday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8264513,
        val: 0,
        val_text: 'Absent',
      },
      {
        id: 632193,
        groupid: '31167',
        course_slot: 5,
        day: '19/01/2022 - Wednesday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8291093,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632194,
        groupid: '31167',
        course_slot: 6,
        day: '07/02/2022 - Monday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8349761,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632195,
        groupid: '31167',
        course_slot: 7,
        day: '09/02/2022 - Wednesday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8379486,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632196,
        groupid: '31167',
        course_slot: 8,
        day: '14/02/2022 - Monday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8439700,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632197,
        groupid: '31167',
        course_slot: 9,
        day: '16/02/2022 - Wednesday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8468074,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632198,
        groupid: '31167',
        course_slot: 10,
        day: '21/02/2022 - Monday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8527578,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632199,
        groupid: '31167',
        course_slot: 11,
        day: '23/02/2022 - Wednesday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành + Kiểm tra',
        done: 1,
        note: '',
        attendance_id: 8554513,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632200,
        groupid: '31167',
        course_slot: 12,
        day: '07/03/2022 - Monday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8597321,
        val: 0,
        val_text: 'Absent',
      },
      {
        id: 632201,
        groupid: '31167',
        course_slot: 13,
        day: '09/03/2022 - Wednesday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8624622,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632202,
        groupid: '31167',
        course_slot: 14,
        day: '14/03/2022 - Monday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8683580,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632203,
        groupid: '31167',
        course_slot: 15,
        day: '16/03/2022 - Wednesday',
        slot: 2,
        leader_login: 'thaottt',
        description: 'Thực hành',
        done: 1,
        note: '',
        attendance_id: 8714923,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 632204,
        groupid: '31167',
        course_slot: 16,
        day: '21/03/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 632205,
        groupid: '31167',
        course_slot: 17,
        day: '23/03/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 632206,
        groupid: '31167',
        course_slot: 18,
        day: '28/03/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 632207,
        groupid: '31167',
        course_slot: 19,
        day: '30/03/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 632208,
        groupid: '31167',
        course_slot: 20,
        day: '04/04/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 632209,
        groupid: '31167',
        course_slot: 21,
        day: '06/04/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 632210,
        groupid: '31167',
        course_slot: 22,
        day: '13/04/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 632211,
        groupid: '31167',
        course_slot: 23,
        day: '18/04/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 632212,
        groupid: '31167',
        course_slot: 150,
        day: '20/04/2022 - Wednesday',
        slot: 0,
        leader_login: '',
        description: 'Thi lần 1',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 632213,
        groupid: '31167',
        course_slot: 201,
        day: '25/04/2022 - Monday',
        slot: 0,
        leader_login: '',
        description: 'Thi lần 2',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
    ],
  },
  {
    member_login: 'dungtmph12934',
    group_id: 31742,
    group_name: 'ENT2225.30',
    subject_code: 'ENT2225',
    skill_code: 'ENT221',
    subject_name: 'Tiếng Anh 2.2',
    subject_id: 655,
    start_date: '11/01/2022',
    total_session: 26,
    total_to_now: 7,
    total_absent: 1,
    activities: [
      {
        id: 645931,
        groupid: '31742',
        course_slot: 1,
        day: '11/01/2022 - Tuesday',
        slot: 5,
        leader_login: 'hoaiht9',
        description: 'Lý thuyết',
        done: 1,
        note: 'Vũ Sơn Huy vào muộn vì nhà có việc bận',
        attendance_id: 8197362,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 645932,
        groupid: '31742',
        course_slot: 2,
        day: '13/01/2022 - Thursday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645933,
        groupid: '31742',
        course_slot: 3,
        day: '15/01/2022 - Saturday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645934,
        groupid: '31742',
        course_slot: 4,
        day: '18/01/2022 - Tuesday',
        slot: 5,
        leader_login: 'hoaiht9',
        description: 'Thực hành',
        done: 1,
        note: 'Vắng 03',
        attendance_id: 8284320,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 645935,
        groupid: '31742',
        course_slot: 5,
        day: '20/01/2022 - Thursday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645936,
        groupid: '31742',
        course_slot: 6,
        day: '22/01/2022 - Saturday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645937,
        groupid: '31742',
        course_slot: 7,
        day: '08/02/2022 - Tuesday',
        slot: 5,
        leader_login: 'hoaiht9',
        description: 'Thực hành',
        done: 1,
        note: 'VẮNG 07',
        attendance_id: 8372311,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 645938,
        groupid: '31742',
        course_slot: 8,
        day: '10/02/2022 - Thursday',
        slot: 0,
        leader_login: '',
        description: 'Remote2',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645939,
        groupid: '31742',
        course_slot: 9,
        day: '12/02/2022 - Saturday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645940,
        groupid: '31742',
        course_slot: 10,
        day: '15/02/2022 - Tuesday',
        slot: 5,
        leader_login: 'hoaiht9',
        description: 'Thực hành',
        done: 1,
        note: 'Vắng 05',
        attendance_id: 8462946,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 645941,
        groupid: '31742',
        course_slot: 11,
        day: '17/02/2022 - Thursday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645942,
        groupid: '31742',
        course_slot: 12,
        day: '19/02/2022 - Saturday',
        slot: 0,
        leader_login: '',
        description: 'Remote2',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645943,
        groupid: '31742',
        course_slot: 13,
        day: '22/02/2022 - Tuesday',
        slot: 5,
        leader_login: 'hoaiht9',
        description: 'Thực hành',
        done: 1,
        note: 'VẮNG 0',
        attendance_id: 8549159,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 645944,
        groupid: '31742',
        course_slot: 14,
        day: '24/02/2022 - Thursday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645945,
        groupid: '31742',
        course_slot: 15,
        day: '26/02/2022 - Saturday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645946,
        groupid: '31742',
        course_slot: 16,
        day: '08/03/2022 - Tuesday',
        slot: 5,
        leader_login: 'hoaiht9',
        description: 'Thực hành',
        done: 1,
        note: 'VẮNG 07',
        attendance_id: 8617907,
        val: 0,
        val_text: 'Absent',
      },
      {
        id: 645947,
        groupid: '31742',
        course_slot: 17,
        day: '10/03/2022 - Thursday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645948,
        groupid: '31742',
        course_slot: 18,
        day: '12/03/2022 - Saturday',
        slot: 0,
        leader_login: '',
        description: 'Remote2',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645949,
        groupid: '31742',
        course_slot: 19,
        day: '15/03/2022 - Tuesday',
        slot: 5,
        leader_login: 'hoaiht9',
        description: 'Thực hành',
        done: 1,
        note: 'vắng 05',
        attendance_id: 8707634,
        val: 1,
        val_text: 'Present',
      },
      {
        id: 645950,
        groupid: '31742',
        course_slot: 20,
        day: '17/03/2022 - Thursday',
        slot: 10,
        leader_login: 'hoaiht9',
        description: 'Giờ học online',
        done: 1,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645951,
        groupid: '31742',
        course_slot: 21,
        day: '19/03/2022 - Saturday',
        slot: 0,
        leader_login: '',
        description: 'Remote2',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645952,
        groupid: '31742',
        course_slot: 22,
        day: '22/03/2022 - Tuesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645953,
        groupid: '31742',
        course_slot: 23,
        day: '24/03/2022 - Thursday',
        slot: 0,
        leader_login: '',
        description: 'Giờ học online',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645954,
        groupid: '31742',
        course_slot: 24,
        day: '26/03/2022 - Saturday',
        slot: 0,
        leader_login: '',
        description: 'Remote2',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645955,
        groupid: '31742',
        course_slot: 25,
        day: '29/03/2022 - Tuesday',
        slot: 0,
        leader_login: '',
        description: 'Thực hành',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645956,
        groupid: '31742',
        course_slot: 26,
        day: '31/03/2022 - Thursday',
        slot: 0,
        leader_login: '',
        description: 'Giờ học online',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645957,
        groupid: '31742',
        course_slot: 150,
        day: '03/04/2022 - Sunday',
        slot: 0,
        leader_login: '',
        description: 'Thi lần 1',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645958,
        groupid: '31742',
        course_slot: 350,
        day: '05/04/2022 - Tuesday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645959,
        groupid: '31742',
        course_slot: 351,
        day: '07/04/2022 - Thursday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
      {
        id: 645960,
        groupid: '31742',
        course_slot: 352,
        day: '09/04/2022 - Saturday',
        slot: 0,
        leader_login: '',
        description: 'Bảo vệ/Dự án',
        done: 0,
        note: '',
        attendance_id: null,
        val: -1,
        val_text: 'Future',
      },
    ],
  },
];

export const dataSchedule = [
  {
    id: 632204,
    day: '21/03/2022 00:00',
    room_name: 'P401',
    area_name: 'TVB',
    subject_code: 'VIE103',
    subject_name: 'Giáo dục thể chất - Vovinam 1',
    group_id: 31167,
    group_name: 'VIE103.02',
    activity_leader_login: 'thaottt',
    slot: 2,
    slot_time: 'Ca 2 (21/03/2022 09:25 - 21/03/2022 11:25)',
    url_room_online: null,
    syllabus_plan_description: 'Thực hành',
    syllabus_plan_noi_dung:
      '* Các thế khóa gỡ trình độ 1: Túm tóc trước tay phải và tay trái\r\n* Thể lực chung',
  },
  {
    id: 627232,
    day: '21/03/2022 00:00',
    room_name: 'P204_Lab',
    area_name: 'TVB',
    subject_code: 'WEB209',
    subject_name: 'Lập trình Front-End Framework 2',
    group_id: 30928,
    group_name: 'WE16202',
    activity_leader_login: 'datlt34',
    slot: 3,
    slot_time: 'Ca 3 (21/03/2022 12:00 - 21/03/2022 14:00)',
    url_room_online: 'https://meet.google.com/feu-nswx-wos?pli=1&authuser=1',
    syllabus_plan_description: 'Tích hợp(LT+TH)',
    syllabus_plan_noi_dung:
      'Slide 4.1: Xử lý đầu vào với Form & Event (P1)\r\nLab4(P1)',
  },
  {
    id: 614613,
    day: '21/03/2022 00:00',
    room_name: 'F202',
    area_name: 'TVB',
    subject_code: 'SYB3011',
    subject_name: 'Khởi sự doanh nghiệp',
    group_id: 30276,
    group_name: 'HM16201',
    activity_leader_login: 'hangptt35',
    slot: 6,
    slot_time: 'Ca 6 (21/03/2022 18:30 - 21/03/2022 20:30)',
    url_room_online: null,
    syllabus_plan_description: 'Thực hành + Kiểm tra',
    syllabus_plan_noi_dung:
      '"\r\nBài 6: Tổ chức và quản lý\r\n- Các loại hình doanh nghiệp\r\n- Trách nhiệm pháp lý và bảo hiểm\r\nTest 1"\r\n',
  },
  {
    id: 645952,
    day: '22/03/2022 00:00',
    room_name: 'F101',
    area_name: 'TVB',
    subject_code: 'ENT2225',
    subject_name: 'Tiếng Anh 2.2',
    group_id: 31742,
    group_name: 'ENT2225.30',
    activity_leader_login: 'hoaiht9',
    slot: 5,
    slot_time: 'Ca 5 (22/03/2022 16:20 - 22/03/2022 18:20)',
    url_room_online: null,
    syllabus_plan_description: 'Thực hành',
    syllabus_plan_noi_dung: 'Communication skills practice 8',
  },
  {
    id: 632205,
    day: '23/03/2022 00:00',
    room_name: 'P401',
    area_name: 'TVB',
    subject_code: 'VIE103',
    subject_name: 'Giáo dục thể chất - Vovinam 1',
    group_id: 31167,
    group_name: 'VIE103.02',
    activity_leader_login: 'thaottt',
    slot: 2,
    slot_time: 'Ca 2 (23/03/2022 09:25 - 23/03/2022 11:25)',
    url_room_online: null,
    syllabus_plan_description: 'Thực hành',
    syllabus_plan_noi_dung:
      '* Các thế khóa gỡ trình độ 1: Túm tóc sau tay phải và tay trái\r\n* Thể lực chung',
  },
  {
    id: 627233,
    day: '23/03/2022 00:00',
    room_name: 'P204_Lab',
    area_name: 'TVB',
    subject_code: 'WEB209',
    subject_name: 'Lập trình Front-End Framework 2',
    group_id: 30928,
    group_name: 'WE16202',
    activity_leader_login: 'datlt34',
    slot: 3,
    slot_time: 'Ca 3 (23/03/2022 12:00 - 23/03/2022 14:00)',
    url_room_online: null,
    syllabus_plan_description: 'Tích hợp(LT+TH)',
    syllabus_plan_noi_dung:
      'Slide 4.2: API request với React (P2)\r\nLab4(P2), Quiz4\r\nNộp bài Assignment giai đoạn 1',
  },
  {
    id: 614614,
    day: '23/03/2022 00:00',
    room_name: 'F202',
    area_name: 'TVB',
    subject_code: 'SYB3011',
    subject_name: 'Khởi sự doanh nghiệp',
    group_id: 30276,
    group_name: 'HM16201',
    activity_leader_login: 'hangptt35',
    slot: 6,
    slot_time: 'Ca 6 (23/03/2022 18:30 - 23/03/2022 20:30)',
    url_room_online: null,
    syllabus_plan_description: 'Thực hành',
    syllabus_plan_noi_dung: 'Đánh giá giai đoạn 1 của bản KHKD\r\n',
  },
  {
    id: 645953,
    day: '24/03/2022 00:00',
    room_name: 'Google Meet 1',
    area_name: 'Google Meet',
    subject_code: 'ENT2225',
    subject_name: 'Tiếng Anh 2.2',
    group_id: 31742,
    group_name: 'ENT2225.30',
    activity_leader_login: 'hoaiht9',
    slot: 10,
    slot_time: 'Ca 10 (24/03/2022 00:00 - 24/03/2022 23:59)',
    url_room_online: null,
    syllabus_plan_description: 'Giờ học online',
    syllabus_plan_noi_dung:
      '"Bài online 10: Discuss ways to improve appearance\r\n- Kĩ năng đọc: diễn giải theo cách khác (paraphrase), đọc hiểu ngữ cảnh (understand from context)\r\n- Kĩ năng nghe để ghi lại thông tin chính (note-taking)"',
  },
  {
    id: 627234,
    day: '25/03/2022 00:00',
    room_name: 'P204_Lab',
    area_name: 'TVB',
    subject_code: 'WEB209',
    subject_name: 'Lập trình Front-End Framework 2',
    group_id: 30928,
    group_name: 'WE16202',
    activity_leader_login: 'datlt34',
    slot: 3,
    slot_time: 'Ca 3 (25/03/2022 12:00 - 25/03/2022 14:00)',
    url_room_online: null,
    syllabus_plan_description: 'Tích hợp(LT+TH)',
    syllabus_plan_noi_dung:
      'Slide 5.1: Redux(P1)\r\n- Redux\r\n- React với Redux\r\nLab5(P1)',
  },
  {
    id: 614615,
    day: '25/03/2022 00:00',
    room_name: 'F202',
    area_name: 'TVB',
    subject_code: 'SYB3011',
    subject_name: 'Khởi sự doanh nghiệp',
    group_id: 30276,
    group_name: 'HM16201',
    activity_leader_login: 'hangptt35',
    slot: 6,
    slot_time: 'Ca 6 (25/03/2022 18:30 - 25/03/2022 20:30)',
    url_room_online: null,
    syllabus_plan_description: 'Thực hành',
    syllabus_plan_noi_dung:
      '"Bài 7: Mua hàng cho doanh nghiệp và kinh doanh xanh\r\n- Mua thiết bị\r\n- Mua nguyên liệu thô\r\n- Mua hàng thành phẩm\r\n- Doanh nghiệp của bạn và tài nguyên thiên nhiên\r\n- Tăng hiệu quả và lợi nhuận: giảm thiểu, tái sử dụng, tái chế"\r\n',
  },
  {
    id: 645954,
    day: '26/03/2022 00:00',
    room_name: 'F101',
    area_name: 'TVB',
    subject_code: 'ENT2225',
    subject_name: 'Tiếng Anh 2.2',
    group_id: 31742,
    group_name: 'ENT2225.30',
    activity_leader_login: 'hoaiht9',
    slot: 8,
    slot_time: 'Ca 8 (26/03/2022 20:30 - 26/03/2022 22:30)',
    url_room_online: null,
    syllabus_plan_description: 'Remote2',
    syllabus_plan_noi_dung: 'Ôn tập',
  },
];
