const newDate = new Date();
export const fakeData = [
  {
    keyIndex: 'Học Tập',
    data: [
      {
        id: 1,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 2,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 3,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 4,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 5,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 6,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 7,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
    ],
  },
  {
    keyIndex: 'Hoạt động',
    data: [
      {
        id: 1,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 2,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 3,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 4,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 5,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 6,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 7,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
    ],
  },
  {
    keyIndex: 'Học phí',
    data: [
      {
        id: 1,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 2,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 3,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 4,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
    ],
  },
  {
    keyIndex: 'Lịch học',
    data: [
      {
        id: 632204,
        day: '21/03/2022 00:00',
        room_name: 'P401',
        area_name: 'TVB',
        subject_code: 'VIE103',
        subject_name: 'Giáo dục thể chất - Vovinam 1',
        group_id: 31167,
        group_name: 'VIE103.02',
        activity_leader_login: 'thaottt',
        slot: 2,
        slot_time: 'Ca 2 (21/03/2022 09:25 - 21/03/2022 11:25)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '* Các thế khóa gỡ trình độ 1: Túm tóc trước tay phải và tay trái\r\n* Thể lực chung',
      },
      {
        id: 627232,
        day: '21/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (21/03/2022 12:00 - 21/03/2022 14:00)',
        url_room_online: 'https://meet.google.com/feu-nswx-wos?pli=1&authuser=1',
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 4.1: Xử lý đầu vào với Form & Event (P1)\r\nLab4(P1)',
      },
      {
        id: 614613,
        day: '21/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (21/03/2022 18:30 - 21/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành + Kiểm tra',
        syllabus_plan_noi_dung:
          '"\r\nBài 6: Tổ chức và quản lý\r\n- Các loại hình doanh nghiệp\r\n- Trách nhiệm pháp lý và bảo hiểm\r\nTest 1"\r\n',
      },
      {
        id: 645952,
        day: '22/03/2022 00:00',
        room_name: 'F101',
        area_name: 'TVB',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 5,
        slot_time: 'Ca 5 (22/03/2022 16:20 - 22/03/2022 18:20)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung: 'Communication skills practice 8',
      },
      {
        id: 632205,
        day: '23/03/2022 00:00',
        room_name: 'P401',
        area_name: 'TVB',
        subject_code: 'VIE103',
        subject_name: 'Giáo dục thể chất - Vovinam 1',
        group_id: 31167,
        group_name: 'VIE103.02',
        activity_leader_login: 'thaottt',
        slot: 2,
        slot_time: 'Ca 2 (23/03/2022 09:25 - 23/03/2022 11:25)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '* Các thế khóa gỡ trình độ 1: Túm tóc sau tay phải và tay trái\r\n* Thể lực chung',
      },
      {
        id: 627233,
        day: '23/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (23/03/2022 12:00 - 23/03/2022 14:00)',
        url_room_online: null,
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 4.2: API request với React (P2)\r\nLab4(P2), Quiz4\r\nNộp bài Assignment giai đoạn 1',
      },
      {
        id: 614614,
        day: '23/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (23/03/2022 18:30 - 23/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung: 'Đánh giá giai đoạn 1 của bản KHKD\r\n',
      },
      {
        id: 645953,
        day: '24/03/2022 00:00',
        room_name: 'Google Meet 1',
        area_name: 'Google Meet',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 10,
        slot_time: 'Ca 10 (24/03/2022 00:00 - 24/03/2022 23:59)',
        url_room_online: null,
        syllabus_plan_description: 'Giờ học online',
        syllabus_plan_noi_dung:
          '"Bài online 10: Discuss ways to improve appearance\r\n- Kĩ năng đọc: diễn giải theo cách khác (paraphrase), đọc hiểu ngữ cảnh (understand from context)\r\n- Kĩ năng nghe để ghi lại thông tin chính (note-taking)"',
      },
      {
        id: 627234,
        day: '25/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (25/03/2022 12:00 - 25/03/2022 14:00)',
        url_room_online: null,
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 5.1: Redux(P1)\r\n- Redux\r\n- React với Redux\r\nLab5(P1)',
      },
      {
        id: 614615,
        day: '25/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (25/03/2022 18:30 - 25/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '"Bài 7: Mua hàng cho doanh nghiệp và kinh doanh xanh\r\n- Mua thiết bị\r\n- Mua nguyên liệu thô\r\n- Mua hàng thành phẩm\r\n- Doanh nghiệp của bạn và tài nguyên thiên nhiên\r\n- Tăng hiệu quả và lợi nhuận: giảm thiểu, tái sử dụng, tái chế"\r\n',
      },
      {
        id: 645954,
        day: '26/03/2022 00:00',
        room_name: 'F101',
        area_name: 'TVB',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 8,
        slot_time: 'Ca 8 (26/03/2022 20:30 - 26/03/2022 22:30)',
        url_room_online: null,
        syllabus_plan_description: 'Remote2',
        syllabus_plan_noi_dung: 'Ôn tập',
      },
    ]
  },
  {
    keyIndex: 'Lịch thi',
    data: [
      {
        id: 632204,
        day: '21/03/2022 00:00',
        room_name: 'P401',
        area_name: 'TVB',
        subject_code: 'VIE103',
        subject_name: 'Giáo dục thể chất - Vovinam 1',
        group_id: 31167,
        group_name: 'VIE103.02',
        activity_leader_login: 'thaottt',
        slot: 2,
        slot_time: 'Ca 2 (21/03/2022 09:25 - 21/03/2022 11:25)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '* Các thế khóa gỡ trình độ 1: Túm tóc trước tay phải và tay trái\r\n* Thể lực chung',
      },
      {
        id: 627232,
        day: '21/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (21/03/2022 12:00 - 21/03/2022 14:00)',
        url_room_online: 'https://meet.google.com/feu-nswx-wos?pli=1&authuser=1',
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 4.1: Xử lý đầu vào với Form & Event (P1)\r\nLab4(P1)',
      },
      {
        id: 614613,
        day: '21/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (21/03/2022 18:30 - 21/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành + Kiểm tra',
        syllabus_plan_noi_dung:
          '"\r\nBài 6: Tổ chức và quản lý\r\n- Các loại hình doanh nghiệp\r\n- Trách nhiệm pháp lý và bảo hiểm\r\nTest 1"\r\n',
      },
      {
        id: 645952,
        day: '22/03/2022 00:00',
        room_name: 'F101',
        area_name: 'TVB',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 5,
        slot_time: 'Ca 5 (22/03/2022 16:20 - 22/03/2022 18:20)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung: 'Communication skills practice 8',
      },
      {
        id: 632205,
        day: '23/03/2022 00:00',
        room_name: 'P401',
        area_name: 'TVB',
        subject_code: 'VIE103',
        subject_name: 'Giáo dục thể chất - Vovinam 1',
        group_id: 31167,
        group_name: 'VIE103.02',
        activity_leader_login: 'thaottt',
        slot: 2,
        slot_time: 'Ca 2 (23/03/2022 09:25 - 23/03/2022 11:25)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '* Các thế khóa gỡ trình độ 1: Túm tóc sau tay phải và tay trái\r\n* Thể lực chung',
      },
      {
        id: 627233,
        day: '23/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (23/03/2022 12:00 - 23/03/2022 14:00)',
        url_room_online: null,
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 4.2: API request với React (P2)\r\nLab4(P2), Quiz4\r\nNộp bài Assignment giai đoạn 1',
      },
      {
        id: 614614,
        day: '23/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (23/03/2022 18:30 - 23/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung: 'Đánh giá giai đoạn 1 của bản KHKD\r\n',
      },
      {
        id: 645953,
        day: '24/03/2022 00:00',
        room_name: 'Google Meet 1',
        area_name: 'Google Meet',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 10,
        slot_time: 'Ca 10 (24/03/2022 00:00 - 24/03/2022 23:59)',
        url_room_online: null,
        syllabus_plan_description: 'Giờ học online',
        syllabus_plan_noi_dung:
          '"Bài online 10: Discuss ways to improve appearance\r\n- Kĩ năng đọc: diễn giải theo cách khác (paraphrase), đọc hiểu ngữ cảnh (understand from context)\r\n- Kĩ năng nghe để ghi lại thông tin chính (note-taking)"',
      },
      {
        id: 627234,
        day: '25/03/2022 00:00',
        room_name: 'P204_Lab',
        area_name: 'TVB',
        subject_code: 'WEB209',
        subject_name: 'Lập trình Front-End Framework 2',
        group_id: 30928,
        group_name: 'WE16202',
        activity_leader_login: 'datlt34',
        slot: 3,
        slot_time: 'Ca 3 (25/03/2022 12:00 - 25/03/2022 14:00)',
        url_room_online: null,
        syllabus_plan_description: 'Tích hợp(LT+TH)',
        syllabus_plan_noi_dung:
          'Slide 5.1: Redux(P1)\r\n- Redux\r\n- React với Redux\r\nLab5(P1)',
      },
      {
        id: 614615,
        day: '25/03/2022 00:00',
        room_name: 'F202',
        area_name: 'TVB',
        subject_code: 'SYB3011',
        subject_name: 'Khởi sự doanh nghiệp',
        group_id: 30276,
        group_name: 'HM16201',
        activity_leader_login: 'hangptt35',
        slot: 6,
        slot_time: 'Ca 6 (25/03/2022 18:30 - 25/03/2022 20:30)',
        url_room_online: null,
        syllabus_plan_description: 'Thực hành',
        syllabus_plan_noi_dung:
          '"Bài 7: Mua hàng cho doanh nghiệp và kinh doanh xanh\r\n- Mua thiết bị\r\n- Mua nguyên liệu thô\r\n- Mua hàng thành phẩm\r\n- Doanh nghiệp của bạn và tài nguyên thiên nhiên\r\n- Tăng hiệu quả và lợi nhuận: giảm thiểu, tái sử dụng, tái chế"\r\n',
      },
      {
        id: 645954,
        day: '26/03/2022 00:00',
        room_name: 'F101',
        area_name: 'TVB',
        subject_code: 'ENT2225',
        subject_name: 'Tiếng Anh 2.2',
        group_id: 31742,
        group_name: 'ENT2225.30',
        activity_leader_login: 'hoaiht9',
        slot: 8,
        slot_time: 'Ca 8 (26/03/2022 20:30 - 26/03/2022 22:30)',
        url_room_online: null,
        syllabus_plan_description: 'Remote2',
        syllabus_plan_noi_dung: 'Ôn tập',
      },
    ]
  },
  {
    keyIndex: 'Điểm danh',
    data: [
      {
        id: 1,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 2,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 3,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
      {
        id: 4,
        title:
          'Thông báo v/v đăng ký học lại ngành công nghệ thông tin tại block 2 kỳ Fall 2020',
        author: 'huongnt166',
        authorTitle: 'Tác giả',
        time: newDate.getDate() + ' @ ' + newDate.getTime(),
        timeTitle: 'Thời gian',
      },
    ],
  },
];



export const dataAttendance = [
  {
    "member_login": "champttph28681",
    "group_id": 29965,
    "group_name": "MA17316",
    "subject_code": "BUS2014",
    "skill_code": "BUS201",
    "subject_name": "Phân tích hoạt động kinh doanh",
    "subject_id": 695,
    "start_date": "04/01/2022",
    "total_session": 16,
    "total_to_now": 16,
    "total_absent": 0,
    "activities": [
      {
        "id": 609589,
        "groupid": "29965",
        "course_slot": 1,
        "day": "04/01/2022 - Tuesday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8119830,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609590,
        "groupid": "29965",
        "course_slot": 2,
        "day": "06/01/2022 - Thursday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8143259,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609591,
        "groupid": "29965",
        "course_slot": 3,
        "day": "08/01/2022 - Saturday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8166852,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609592,
        "groupid": "29965",
        "course_slot": 4,
        "day": "11/01/2022 - Tuesday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Thực hành",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8196634,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609593,
        "groupid": "29965",
        "course_slot": 5,
        "day": "13/01/2022 - Thursday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8224906,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609594,
        "groupid": "29965",
        "course_slot": 6,
        "day": "15/01/2022 - Saturday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8254256,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609595,
        "groupid": "29965",
        "course_slot": 7,
        "day": "18/01/2022 - Tuesday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết + Kiểm tra",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8283356,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609596,
        "groupid": "29965",
        "course_slot": 8,
        "day": "20/01/2022 - Thursday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Thực hành",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8312500,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609597,
        "groupid": "29965",
        "course_slot": 9,
        "day": "22/01/2022 - Saturday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8341563,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609598,
        "groupid": "29965",
        "course_slot": 10,
        "day": "08/02/2022 - Tuesday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8371290,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609599,
        "groupid": "29965",
        "course_slot": 11,
        "day": "10/02/2022 - Thursday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8400746,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609600,
        "groupid": "29965",
        "course_slot": 12,
        "day": "12/02/2022 - Saturday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Thực hành",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8430188,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609601,
        "groupid": "29965",
        "course_slot": 13,
        "day": "15/02/2022 - Tuesday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8459238,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609602,
        "groupid": "29965",
        "course_slot": 14,
        "day": "17/02/2022 - Thursday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8490521,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609603,
        "groupid": "29965",
        "course_slot": 15,
        "day": "19/02/2022 - Saturday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Lý thuyết + Kiểm tra",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8518409,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609604,
        "groupid": "29965",
        "course_slot": 16,
        "day": "22/02/2022 - Tuesday",
        "slot": 4,
        "leader_login": "anhnd73",
        "description": "Thực hành",
        "done": 1,
        "note": "Bình thường",
        "attendance_id": 8547685,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 609605,
        "groupid": "29965",
        "course_slot": 300,
        "day": "26/02/2022 - Saturday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 609606,
        "groupid": "29965",
        "course_slot": 301,
        "day": "01/03/2022 - Tuesday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 609607,
        "groupid": "29965",
        "course_slot": 302,
        "day": "03/03/2022 - Thursday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      }
    ]
  },
  {
    "member_login": "champttph28681",
    "group_id": 30024,
    "group_name": "MA17301",
    "subject_code": "BUS1024",
    "skill_code": "BUS102",
    "subject_name": "Kinh tế",
    "subject_id": 589,
    "start_date": "04/01/2022",
    "total_session": 21,
    "total_to_now": 6,
    "total_absent": 1,
    "activities": [
      {
        "id": 610466,
        "groupid": "30024",
        "course_slot": 1,
        "day": "04/01/2022 - Tuesday",
        "slot": 3,
        "leader_login": "hanq9",
        "description": "Remote",
        "done": 1,
        "note": "",
        "attendance_id": 8116364,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 610467,
        "groupid": "30024",
        "course_slot": 2,
        "day": "05/01/2022 - Wednesday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610468,
        "groupid": "30024",
        "course_slot": 3,
        "day": "06/01/2022 - Thursday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610469,
        "groupid": "30024",
        "course_slot": 4,
        "day": "08/01/2022 - Saturday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610470,
        "groupid": "30024",
        "course_slot": 5,
        "day": "11/01/2022 - Tuesday",
        "slot": 3,
        "leader_login": "hanq9",
        "description": "Remote",
        "done": 1,
        "note": "",
        "attendance_id": 8193629,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 610471,
        "groupid": "30024",
        "course_slot": 6,
        "day": "12/01/2022 - Wednesday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610472,
        "groupid": "30024",
        "course_slot": 7,
        "day": "13/01/2022 - Thursday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610473,
        "groupid": "30024",
        "course_slot": 8,
        "day": "15/01/2022 - Saturday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610474,
        "groupid": "30024",
        "course_slot": 9,
        "day": "18/01/2022 - Tuesday",
        "slot": 3,
        "leader_login": "hanq9",
        "description": "Remote",
        "done": 1,
        "note": "",
        "attendance_id": 8281059,
        "val": 0,
        "val_text": "Absent"
      },
      {
        "id": 610475,
        "groupid": "30024",
        "course_slot": 10,
        "day": "19/01/2022 - Wednesday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610476,
        "groupid": "30024",
        "course_slot": 11,
        "day": "20/01/2022 - Thursday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610477,
        "groupid": "30024",
        "course_slot": 12,
        "day": "22/01/2022 - Saturday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610478,
        "groupid": "30024",
        "course_slot": 13,
        "day": "08/02/2022 - Tuesday",
        "slot": 3,
        "leader_login": "hanq9",
        "description": "Remote",
        "done": 1,
        "note": "",
        "attendance_id": 8368261,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 610479,
        "groupid": "30024",
        "course_slot": 14,
        "day": "09/02/2022 - Wednesday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610480,
        "groupid": "30024",
        "course_slot": 15,
        "day": "10/02/2022 - Thursday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610481,
        "groupid": "30024",
        "course_slot": 16,
        "day": "12/02/2022 - Saturday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610482,
        "groupid": "30024",
        "course_slot": 17,
        "day": "15/02/2022 - Tuesday",
        "slot": 3,
        "leader_login": "hanq9",
        "description": "Remote",
        "done": 1,
        "note": "",
        "attendance_id": 8457736,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 610483,
        "groupid": "30024",
        "course_slot": 18,
        "day": "16/02/2022 - Wednesday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610484,
        "groupid": "30024",
        "course_slot": 19,
        "day": "17/02/2022 - Thursday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610485,
        "groupid": "30024",
        "course_slot": 20,
        "day": "19/02/2022 - Saturday",
        "slot": 10,
        "leader_login": "hanq9",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 610486,
        "groupid": "30024",
        "course_slot": 21,
        "day": "22/02/2022 - Tuesday",
        "slot": 3,
        "leader_login": "hanq9",
        "description": "Remote",
        "done": 1,
        "note": "",
        "attendance_id": 8543835,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 610487,
        "groupid": "30024",
        "course_slot": 150,
        "day": "06/03/2022 - Sunday",
        "slot": 0,
        "leader_login": "",
        "description": "Thi lần 1",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      }
    ]
  },
  {
    "member_login": "champttph28681",
    "group_id": 30114,
    "group_name": "MA17301",
    "subject_code": "MAR2023",
    "skill_code": "MAR202",
    "subject_name": "Nghiên cứu Marketing",
    "subject_id": 420,
    "start_date": "08/03/2022",
    "total_session": 16,
    "total_to_now": 9,
    "total_absent": 1,
    "activities": [
      {
        "id": 611861,
        "groupid": "30114",
        "course_slot": 1,
        "day": "08/03/2022 - Tuesday",
        "slot": 3,
        "leader_login": "huonghtng",
        "description": "Lý thuyết",
        "done": 1,
        "note": "khong",
        "attendance_id": 8613173,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611862,
        "groupid": "30114",
        "course_slot": 2,
        "day": "10/03/2022 - Thursday",
        "slot": 3,
        "leader_login": "huonghtng",
        "description": "Lý thuyết",
        "done": 1,
        "note": "KHONG",
        "attendance_id": 8642520,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611863,
        "groupid": "30114",
        "course_slot": 3,
        "day": "12/03/2022 - Saturday",
        "slot": 3,
        "leader_login": "huonghtng",
        "description": "Lý thuyết",
        "done": 1,
        "note": "KHONG",
        "attendance_id": 8672245,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611864,
        "groupid": "30114",
        "course_slot": 4,
        "day": "15/03/2022 - Tuesday",
        "slot": 3,
        "leader_login": "huonghtng",
        "description": "Lý thuyết",
        "done": 1,
        "note": "KHONG",
        "attendance_id": 8702637,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611865,
        "groupid": "30114",
        "course_slot": 5,
        "day": "17/03/2022 - Thursday",
        "slot": 3,
        "leader_login": "huonghtng",
        "description": "Lý thuyết",
        "done": 1,
        "note": "KHONG",
        "attendance_id": 8734829,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611866,
        "groupid": "30114",
        "course_slot": 6,
        "day": "19/03/2022 - Saturday",
        "slot": 3,
        "leader_login": "huonghtng",
        "description": "Thực hành",
        "done": 1,
        "note": "KHONG",
        "attendance_id": 8765651,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611867,
        "groupid": "30114",
        "course_slot": 7,
        "day": "22/03/2022 - Tuesday",
        "slot": 3,
        "leader_login": "huonghtng",
        "description": "Lý thuyết + Kiểm tra",
        "done": 1,
        "note": "KHONG",
        "attendance_id": 8796841,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611868,
        "groupid": "30114",
        "course_slot": 8,
        "day": "24/03/2022 - Thursday",
        "slot": 3,
        "leader_login": "huonghtng",
        "description": "Lý thuyết",
        "done": 1,
        "note": "khong",
        "attendance_id": 8830521,
        "val": 0,
        "val_text": "Absent"
      },
      {
        "id": 611869,
        "groupid": "30114",
        "course_slot": 9,
        "day": "26/03/2022 - Saturday",
        "slot": 3,
        "leader_login": "huonghtng",
        "description": "Lý thuyết",
        "done": 1,
        "note": "KHONG",
        "attendance_id": 8861238,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611870,
        "groupid": "30114",
        "course_slot": 10,
        "day": "29/03/2022 - Tuesday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611871,
        "groupid": "30114",
        "course_slot": 11,
        "day": "31/03/2022 - Thursday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611872,
        "groupid": "30114",
        "course_slot": 12,
        "day": "02/04/2022 - Saturday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611873,
        "groupid": "30114",
        "course_slot": 13,
        "day": "05/04/2022 - Tuesday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611874,
        "groupid": "30114",
        "course_slot": 14,
        "day": "07/04/2022 - Thursday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611875,
        "groupid": "30114",
        "course_slot": 15,
        "day": "09/04/2022 - Saturday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết + Kiểm tra",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611876,
        "groupid": "30114",
        "course_slot": 16,
        "day": "12/04/2022 - Tuesday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611877,
        "groupid": "30114",
        "course_slot": 300,
        "day": "16/04/2022 - Saturday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611878,
        "groupid": "30114",
        "course_slot": 301,
        "day": "19/04/2022 - Tuesday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611879,
        "groupid": "30114",
        "course_slot": 302,
        "day": "21/04/2022 - Thursday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      }
    ]
  },
  {
    "member_login": "champttph28681",
    "group_id": 30117,
    "group_name": "MA17302",
    "subject_code": "PRE106",
    "skill_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "subject_id": 432,
    "start_date": "08/03/2022",
    "total_session": 16,
    "total_to_now": 9,
    "total_absent": 1,
    "activities": [
      {
        "id": 611918,
        "groupid": "30117",
        "course_slot": 1,
        "day": "08/03/2022 - Tuesday",
        "slot": 4,
        "leader_login": "tuyetna3",
        "description": "Lý thuyết",
        "done": 1,
        "note": "",
        "attendance_id": 8615994,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611919,
        "groupid": "30117",
        "course_slot": 2,
        "day": "10/03/2022 - Thursday",
        "slot": 4,
        "leader_login": "tuyetna3",
        "description": "Lý thuyết",
        "done": 1,
        "note": "",
        "attendance_id": 8645959,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611920,
        "groupid": "30117",
        "course_slot": 3,
        "day": "12/03/2022 - Saturday",
        "slot": 4,
        "leader_login": "tuyetna3",
        "description": "Lý thuyết",
        "done": 1,
        "note": "",
        "attendance_id": 8674942,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611921,
        "groupid": "30117",
        "course_slot": 4,
        "day": "15/03/2022 - Tuesday",
        "slot": 4,
        "leader_login": "tuyetna3",
        "description": "Lý thuyết",
        "done": 1,
        "note": "",
        "attendance_id": 8705425,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611922,
        "groupid": "30117",
        "course_slot": 5,
        "day": "17/03/2022 - Thursday",
        "slot": 4,
        "leader_login": "tuyetna3",
        "description": "Lý thuyết",
        "done": 1,
        "note": "",
        "attendance_id": 8737871,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611923,
        "groupid": "30117",
        "course_slot": 6,
        "day": "19/03/2022 - Saturday",
        "slot": 4,
        "leader_login": "tuyetna3",
        "description": "Lý thuyết",
        "done": 1,
        "note": "",
        "attendance_id": 8770181,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611924,
        "groupid": "30117",
        "course_slot": 7,
        "day": "22/03/2022 - Tuesday",
        "slot": 4,
        "leader_login": "tuyetna3",
        "description": "Lý thuyết + Kiểm tra",
        "done": 1,
        "note": "",
        "attendance_id": 8800375,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611925,
        "groupid": "30117",
        "course_slot": 8,
        "day": "24/03/2022 - Thursday",
        "slot": 4,
        "leader_login": "tuyetna3",
        "description": "Lý thuyết",
        "done": 1,
        "note": "",
        "attendance_id": 8832503,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 611926,
        "groupid": "30117",
        "course_slot": 9,
        "day": "26/03/2022 - Saturday",
        "slot": 4,
        "leader_login": "tuyetna3",
        "description": "Lý thuyết",
        "done": 1,
        "note": "",
        "attendance_id": 8864419,
        "val": 0,
        "val_text": "Absent"
      },
      {
        "id": 611927,
        "groupid": "30117",
        "course_slot": 10,
        "day": "29/03/2022 - Tuesday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611928,
        "groupid": "30117",
        "course_slot": 11,
        "day": "31/03/2022 - Thursday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611929,
        "groupid": "30117",
        "course_slot": 12,
        "day": "02/04/2022 - Saturday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611930,
        "groupid": "30117",
        "course_slot": 13,
        "day": "05/04/2022 - Tuesday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611931,
        "groupid": "30117",
        "course_slot": 14,
        "day": "07/04/2022 - Thursday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611932,
        "groupid": "30117",
        "course_slot": 15,
        "day": "09/04/2022 - Saturday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết + Kiểm tra",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611933,
        "groupid": "30117",
        "course_slot": 16,
        "day": "12/04/2022 - Tuesday",
        "slot": 0,
        "leader_login": "",
        "description": "Lý thuyết",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611934,
        "groupid": "30117",
        "course_slot": 300,
        "day": "16/04/2022 - Saturday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611935,
        "groupid": "30117",
        "course_slot": 301,
        "day": "19/04/2022 - Tuesday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 611936,
        "groupid": "30117",
        "course_slot": 302,
        "day": "21/04/2022 - Thursday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      }
    ]
  },
  {
    "member_login": "champttph28681",
    "group_id": 31457,
    "group_name": "ENT1225.253",
    "subject_code": "ENT1225",
    "skill_code": "ENT121",
    "subject_name": "Tiếng Anh 1.2",
    "subject_id": 591,
    "start_date": "14/01/2022",
    "total_session": 26,
    "total_to_now": 8,
    "total_absent": 1,
    "activities": [
      {
        "id": 639387,
        "groupid": "31457",
        "course_slot": 1,
        "day": "14/01/2022 - Friday",
        "slot": 5,
        "leader_login": "huongbtx3",
        "description": "Lý thuyết",
        "done": 1,
        "note": "",
        "attendance_id": 8242440,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 639388,
        "groupid": "31457",
        "course_slot": 2,
        "day": "17/01/2022 - Monday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639389,
        "groupid": "31457",
        "course_slot": 3,
        "day": "19/01/2022 - Wednesday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639390,
        "groupid": "31457",
        "course_slot": 4,
        "day": "21/01/2022 - Friday",
        "slot": 5,
        "leader_login": "huongbtx3",
        "description": "Thực hành",
        "done": 1,
        "note": "",
        "attendance_id": 8328871,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 639391,
        "groupid": "31457",
        "course_slot": 5,
        "day": "07/02/2022 - Monday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639392,
        "groupid": "31457",
        "course_slot": 6,
        "day": "09/02/2022 - Wednesday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639393,
        "groupid": "31457",
        "course_slot": 7,
        "day": "11/02/2022 - Friday",
        "slot": 5,
        "leader_login": "huongbtx3",
        "description": "Thực hành",
        "done": 1,
        "note": "",
        "attendance_id": 8416704,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 639394,
        "groupid": "31457",
        "course_slot": 8,
        "day": "14/02/2022 - Monday",
        "slot": 8,
        "leader_login": "huongbtx3",
        "description": "Remote2",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639395,
        "groupid": "31457",
        "course_slot": 9,
        "day": "16/02/2022 - Wednesday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639396,
        "groupid": "31457",
        "course_slot": 10,
        "day": "18/02/2022 - Friday",
        "slot": 5,
        "leader_login": "huongbtx3",
        "description": "Thực hành",
        "done": 1,
        "note": "",
        "attendance_id": 8507029,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 639397,
        "groupid": "31457",
        "course_slot": 11,
        "day": "21/02/2022 - Monday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639398,
        "groupid": "31457",
        "course_slot": 12,
        "day": "23/02/2022 - Wednesday",
        "slot": 8,
        "leader_login": "huongbtx3",
        "description": "Remote2",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639399,
        "groupid": "31457",
        "course_slot": 13,
        "day": "25/02/2022 - Friday",
        "slot": 5,
        "leader_login": "huongbtx3",
        "description": "Thực hành",
        "done": 1,
        "note": "",
        "attendance_id": 8582517,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 639400,
        "groupid": "31457",
        "course_slot": 14,
        "day": "07/03/2022 - Monday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639401,
        "groupid": "31457",
        "course_slot": 15,
        "day": "09/03/2022 - Wednesday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639402,
        "groupid": "31457",
        "course_slot": 16,
        "day": "11/03/2022 - Friday",
        "slot": 5,
        "leader_login": "huongbtx3",
        "description": "Thực hành",
        "done": 1,
        "note": "",
        "attendance_id": 8662250,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 639403,
        "groupid": "31457",
        "course_slot": 17,
        "day": "14/03/2022 - Monday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639404,
        "groupid": "31457",
        "course_slot": 18,
        "day": "16/03/2022 - Wednesday",
        "slot": 8,
        "leader_login": "huongbtx3",
        "description": "Remote2",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639405,
        "groupid": "31457",
        "course_slot": 19,
        "day": "18/03/2022 - Friday",
        "slot": 5,
        "leader_login": "huongbtx3",
        "description": "Thực hành",
        "done": 1,
        "note": "",
        "attendance_id": 8756361,
        "val": 0,
        "val_text": "Absent"
      },
      {
        "id": 639406,
        "groupid": "31457",
        "course_slot": 20,
        "day": "21/03/2022 - Monday",
        "slot": 10,
        "leader_login": "huongbtx3",
        "description": "Giờ học online",
        "done": 1,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639407,
        "groupid": "31457",
        "course_slot": 21,
        "day": "23/03/2022 - Wednesday",
        "slot": 0,
        "leader_login": "",
        "description": "Remote2",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639408,
        "groupid": "31457",
        "course_slot": 22,
        "day": "25/03/2022 - Friday",
        "slot": 5,
        "leader_login": "huongbtx3",
        "description": "Thực hành",
        "done": 1,
        "note": "",
        "attendance_id": 8851072,
        "val": 1,
        "val_text": "Present"
      },
      {
        "id": 639409,
        "groupid": "31457",
        "course_slot": 23,
        "day": "28/03/2022 - Monday",
        "slot": 0,
        "leader_login": "",
        "description": "Giờ học online",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639410,
        "groupid": "31457",
        "course_slot": 24,
        "day": "30/03/2022 - Wednesday",
        "slot": 0,
        "leader_login": "",
        "description": "Remote2",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639411,
        "groupid": "31457",
        "course_slot": 25,
        "day": "01/04/2022 - Friday",
        "slot": 0,
        "leader_login": "",
        "description": "Thực hành",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639412,
        "groupid": "31457",
        "course_slot": 26,
        "day": "01/04/2022 - Friday",
        "slot": 0,
        "leader_login": "",
        "description": "Giờ học online",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639413,
        "groupid": "31457",
        "course_slot": 150,
        "day": "17/04/2022 - Sunday",
        "slot": 0,
        "leader_login": "",
        "description": "Thi lần 1",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639414,
        "groupid": "31457",
        "course_slot": 350,
        "day": "08/04/2022 - Friday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639415,
        "groupid": "31457",
        "course_slot": 351,
        "day": "13/04/2022 - Wednesday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      },
      {
        "id": 639416,
        "groupid": "31457",
        "course_slot": 352,
        "day": "15/04/2022 - Friday",
        "slot": 0,
        "leader_login": "",
        "description": "Bảo vệ/Dự án",
        "done": 0,
        "note": "",
        "attendance_id": null,
        "val": -1,
        "val_text": "Future"
      }
    ]
  }
]

export const dataSchedule = [
  {
    "id": 611869,
    "day": "26/03/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (26/03/2022 12:00 - 26/03/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài online 7: Đo lường và đánh giá trong nghiên cứu Marketing                                                 - Bản chất, các loại thang đo lường cơ bản và tiêu chuẩn của đo lường \r\n- Phương pháp đo lường và đánh giá mặt định tính của các đối tượng\r\n- Phương pháp đo lường và đánh giá tầm quan trọng của các thuộc tính \r\n- Quyết định về các hạng mục được lựa chọn loại thang điểm trong đánh giá"
  },
  {
    "id": 611926,
    "day": "26/03/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (26/03/2022 14:10 - 26/03/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài 6\r\nChương 5: Cảm nhận, Nhận thức và Cảm xúc\r\n- Cảm nhận\r\n- Nhận thức\r\n- Cảm xúc"
  },
  {
    "id": 639409,
    "day": "28/03/2022 00:00",
    "room_name": "Google Meet 1",
    "area_name": "Google Meet",
    "subject_code": "ENT1225",
    "subject_name": "Tiếng Anh 1.2",
    "group_id": 31457,
    "group_name": "ENT1225.253",
    "activity_leader_login": "huongbtx3",
    "slot": 10,
    "slot_time": "Ca 10 (28/03/2022 00:00 - 28/03/2022 23:59)",
    "url_room_online": null,
    "syllabus_plan_description": "Giờ học online",
    "syllabus_plan_noi_dung": "\"Bài online 10: Technology\r\n - Mô tả sự cố kỹ thuật của một loại thiết bị gia dụng/đồ điện tử\r\n - Cách thể hiện sự thông cảm\r\n - Thì hiện tại tiếp diễn dùng để miêu tả sự cố\""
  },
  {
    "id": 611870,
    "day": "29/03/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (29/03/2022 12:00 - 29/03/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài online 8: Thiết kế bảng câu hỏi trong nghiên cứu Marketing                                                                                                                                                                                                                             - Bảng câu hỏi và thiết kế bảng câu hỏi\r\n- Quy trình thiết kế bảng câu hỏi                                                                                                                                                                                                                                                                                                  \r\n- Các dạng câu hỏi\r\n- Những yêu cầu cơ bản khi thiết kế bảng câu hỏi"
  },
  {
    "id": 611927,
    "day": "29/03/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (29/03/2022 14:10 - 29/03/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài 7\r\nChương 5: Cảm nhận, Nhận thức và Cảm xúc (tiếp)\r\n- Các lỗi nhận thức \r\n- Ảnh hưởng của tâm trạng, cảm xúc tới kết quả của cuộc đàm phán\r\n- Nội dung được trao đổi trong cuộc đàm phán"
  },
  {
    "id": 639410,
    "day": "30/03/2022 00:00",
    "room_name": "Google Meet 1",
    "area_name": "Google Meet",
    "subject_code": "ENT1225",
    "subject_name": "Tiếng Anh 1.2",
    "group_id": 31457,
    "group_name": "ENT1225.253",
    "activity_leader_login": "huongbtx3",
    "slot": 8,
    "slot_time": "Ca 8 (30/03/2022 20:30 - 30/03/2022 22:30)",
    "url_room_online": null,
    "syllabus_plan_description": "Remote2",
    "syllabus_plan_noi_dung": "Ôn tập"
  },
  {
    "id": 611871,
    "day": "31/03/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (31/03/2022 12:00 - 31/03/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài online 9: Chọn mẫu trong nghiên cứu Marketing                                                                                                                                                                                                                                                       - Khái quát về chọn mẫu \r\n- Quy trình chọn mẫu \r\n- Các phương pháp chọn mẫu \r\n- Xác định kích thước mẫu\r\n"
  },
  {
    "id": 611928,
    "day": "31/03/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (31/03/2022 14:10 - 31/03/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài 8\r\nChương 6: Giao tiếp\r\n- Các đặc điểm ngôn ngữ\r\n- Các loại ngôn ngữ và \r\n- Kênh giao tiếp thường được sử dụng trong đàm phán\r\n- Các công cụ thực tiễn để cải thiện quá trình giao tiếp trong cuộc đàm phán"
  },
  {
    "id": 639411,
    "day": "01/04/2022 00:00",
    "room_name": "L303",
    "area_name": "TVB",
    "subject_code": "ENT1225",
    "subject_name": "Tiếng Anh 1.2",
    "group_id": 31457,
    "group_name": "ENT1225.253",
    "activity_leader_login": "huongbtx3",
    "slot": 5,
    "slot_time": "Ca 5 (01/04/2022 16:20 - 01/04/2022 18:20)",
    "url_room_online": null,
    "syllabus_plan_description": "Thực hành",
    "syllabus_plan_noi_dung": "Communication skills practice 9"
  },
  {
    "id": 639412,
    "day": "01/04/2022 00:00",
    "room_name": "Google Meet 1",
    "area_name": "Google Meet",
    "subject_code": "ENT1225",
    "subject_name": "Tiếng Anh 1.2",
    "group_id": 31457,
    "group_name": "ENT1225.253",
    "activity_leader_login": "huongbtx3",
    "slot": 10,
    "slot_time": "Ca 10 (01/04/2022 00:00 - 01/04/2022 23:59)",
    "url_room_online": null,
    "syllabus_plan_description": "Giờ học online",
    "syllabus_plan_noi_dung": "Online lesson revision"
  },
  {
    "id": 611872,
    "day": "02/04/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (02/04/2022 12:00 - 02/04/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "- Nhận xét sản phẩm N3 của Assignment\r\n- Hướng dẫn sản phẩm N4 của Assignment"
  },
  {
    "id": 611929,
    "day": "02/04/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (02/04/2022 14:10 - 02/04/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài 9\r\nChương 7: Tìm kiếm và sử dụng quyền lực đàm phán\r\n- Định nghĩa “quyền lực” trong các cuộc đàm phán và tại sao quyền lực lại quan trọng trong đàm phán. \r\n- Các nguồn lực và nền tảng khác nhau của quyền lực trong đàm phán\r\n- Các loại quyền lực\r\n- Phương pháp tiếp cận chiến lược với nhà đàm phán nhiều quyền lực hơn"
  },
  {
    "id": 611873,
    "day": "05/04/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (05/04/2022 12:00 - 05/04/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài online 10: Xử lý và phân tích dữ liệu                                                                                                                                                                                                                                                                         - Chuẩn bị dữ liệu                                                                                                                                                                                                                                                                                                   \r\n- Phân tích và giải thích dữ liệu                                                                                                                                                                                                                                            \r\n- Nội dung các phương pháp phân tích dữ liệu "
  },
  {
    "id": 611930,
    "day": "05/04/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (05/04/2022 14:10 - 05/04/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "- Nhận xét sản phẩm N3 của Assignment\r\n- Hướng dẫn sản phẩm N4 của Assignment"
  },
  {
    "id": 611874,
    "day": "07/04/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (07/04/2022 12:00 - 07/04/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài online 10: Xử lý và phân tích dữ liệu (tt)\r\n- Xử lý số liệu bằng SPSS/Excel                                                                                                                                                                                                                                                                        "
  },
  {
    "id": 611931,
    "day": "07/04/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (07/04/2022 14:10 - 07/04/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Bài 10\r\nChương 8: Mối quan hệ trong đàm phán\r\n- Tác động của mối quan hệ tới cuộc đàm phán\r\n- Các hình thức khác nhau của các mối quan hệ trong đó đàm phán có thể xuất hiện\r\n- Vai trò của danh tiếng, sự tin cậy, và công bằng trong mối quan hệ đàm phán"
  },
  {
    "id": 639414,
    "day": "08/04/2022 00:00",
    "room_name": "L304",
    "area_name": "TVB",
    "subject_code": "ENT1225",
    "subject_name": "Tiếng Anh 1.2",
    "group_id": 31457,
    "group_name": "ENT1225.253",
    "activity_leader_login": "gva306",
    "slot": 5,
    "slot_time": "Ca 5 (08/04/2022 16:20 - 08/04/2022 18:20)",
    "url_room_online": null,
    "syllabus_plan_description": "Bảo vệ/Dự án",
    "syllabus_plan_noi_dung": "Thi Oral test buổi 1"
  },
  {
    "id": 611875,
    "day": "09/04/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (09/04/2022 12:00 - 09/04/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết + Kiểm tra",
    "syllabus_plan_noi_dung": "Bài online 11: Trình bày và báo cáo kết quả nghiên cứu                                                                                                                                                                                                                                                 - Định hướng, yêu cầu và chức năng của một bản báo cáo\r\n- Kết cấu và nội dung của báo cáo\r\n- Thiết kế việc viết báo cáo \r\n- Thuyết trình kết quả nghiên cứu\r\nTest 2 (30') (Mục 6.3, 6.4 chương 6 và chương 7, 8, 9, 10, 11)"
  },
  {
    "id": 611932,
    "day": "09/04/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (09/04/2022 14:10 - 09/04/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết + Kiểm tra",
    "syllabus_plan_noi_dung": "Bài 11\r\nChương 10: Thông lệ tốt nhất trong đàm phán\r\nTest 2 (30') (Bài online 6,7,8,9,10,11)"
  },
  {
    "id": 611876,
    "day": "12/04/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (12/04/2022 12:00 - 12/04/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Đánh giá giai đoạn 2 của Assignment bao gồm sản phẩm N3 và N4"
  },
  {
    "id": 611933,
    "day": "12/04/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (12/04/2022 14:10 - 12/04/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Lý thuyết",
    "syllabus_plan_noi_dung": "Đánh giá giai đoạn 2 của Assignment bao gồm sản phẩm N3 và N4"
  },
  {
    "id": 639415,
    "day": "13/04/2022 00:00",
    "room_name": "L304",
    "area_name": "TVB",
    "subject_code": "ENT1225",
    "subject_name": "Tiếng Anh 1.2",
    "group_id": 31457,
    "group_name": "ENT1225.253",
    "activity_leader_login": "gva306",
    "slot": 5,
    "slot_time": "Ca 5 (13/04/2022 16:20 - 13/04/2022 18:20)",
    "url_room_online": null,
    "syllabus_plan_description": "Bảo vệ/Dự án",
    "syllabus_plan_noi_dung": "Thi Oral test buổi 2"
  },
  {
    "id": 639416,
    "day": "15/04/2022 00:00",
    "room_name": "F102",
    "area_name": "TVB",
    "subject_code": "ENT1225",
    "subject_name": "Tiếng Anh 1.2",
    "group_id": 31457,
    "group_name": "ENT1225.253",
    "activity_leader_login": "gva306",
    "slot": 5,
    "slot_time": "Ca 5 (15/04/2022 16:20 - 15/04/2022 18:20)",
    "url_room_online": null,
    "syllabus_plan_description": "Bảo vệ/Dự án",
    "syllabus_plan_noi_dung": "Thi Oral test buổi 3"
  },
  {
    "id": 611877,
    "day": "16/04/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (16/04/2022 12:00 - 16/04/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Bảo vệ/Dự án",
    "syllabus_plan_noi_dung": "Bảo vệ Assignment (Số lượng buổi bảo vệ tùy thuộc vào số lượng sinh viên của lớp và thỏa mãn: 13 sinh viên/buổi bảo vệ, tối đa 3 buổi bảo vệ)"
  },
  {
    "id": 611934,
    "day": "16/04/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (16/04/2022 14:10 - 16/04/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Bảo vệ/Dự án",
    "syllabus_plan_noi_dung": "Bảo vệ Assignment (Số lượng buổi bảo vệ tùy thuộc vào số lượng sinh viên của lớp và thỏa mãn: 13 sinh viên/buổi bảo vệ, tối đa 3 buổi bảo vệ)"
  },
  {
    "id": 639413,
    "day": "17/04/2022 00:00",
    "room_name": "P203_Lab",
    "area_name": "TVB",
    "subject_code": "ENT1225",
    "subject_name": "Tiếng Anh 1.2",
    "group_id": 31457,
    "group_name": "ENT1225.253",
    "activity_leader_login": "gva306",
    "slot": 5,
    "slot_time": "Ca 5 (17/04/2022 16:20 - 17/04/2022 18:20)",
    "url_room_online": null,
    "syllabus_plan_description": "Thi lần 1",
    "syllabus_plan_noi_dung": "Thi General test (trắc nghiệm)"
  },
  {
    "id": 611878,
    "day": "19/04/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (19/04/2022 12:00 - 19/04/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Bảo vệ/Dự án",
    "syllabus_plan_noi_dung": "Bảo vệ Assignment (Số lượng buổi bảo vệ tùy thuộc vào số lượng sinh viên của lớp và thỏa mãn: 13 sinh viên/buổi bảo vệ, tối đa 3 buổi bảo vệ)"
  },
  {
    "id": 611935,
    "day": "19/04/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (19/04/2022 14:10 - 19/04/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Bảo vệ/Dự án",
    "syllabus_plan_noi_dung": "Bảo vệ Assignment (Số lượng buổi bảo vệ tùy thuộc vào số lượng sinh viên của lớp và thỏa mãn: 13 sinh viên/buổi bảo vệ, tối đa 3 buổi bảo vệ)"
  },
  {
    "id": 611879,
    "day": "21/04/2022 00:00",
    "room_name": "L105",
    "area_name": "TVB",
    "subject_code": "MAR2023",
    "subject_name": "Nghiên cứu Marketing",
    "group_id": 30114,
    "group_name": "MA17301",
    "activity_leader_login": "huonghtng",
    "slot": 3,
    "slot_time": "Ca 3 (21/04/2022 12:00 - 21/04/2022 14:00)",
    "url_room_online": null,
    "syllabus_plan_description": "Bảo vệ/Dự án",
    "syllabus_plan_noi_dung": "Bảo vệ Assignment (Số lượng buổi bảo vệ tùy thuộc vào số lượng sinh viên của lớp và thỏa mãn: 13 sinh viên/buổi bảo vệ, tối đa 3 buổi bảo vệ)"
  },
  {
    "id": 611936,
    "day": "21/04/2022 00:00",
    "room_name": "P205",
    "area_name": "TVB",
    "subject_code": "PRE106",
    "subject_name": "Kỹ năng đàm phán",
    "group_id": 30117,
    "group_name": "MA17302",
    "activity_leader_login": "tuyetna3",
    "slot": 4,
    "slot_time": "Ca 4 (21/04/2022 14:10 - 21/04/2022 16:10)",
    "url_room_online": null,
    "syllabus_plan_description": "Bảo vệ/Dự án",
    "syllabus_plan_noi_dung": "Bảo vệ Assignment (Số lượng buổi bảo vệ tùy thuộc vào số lượng sinh viên của lớp và thỏa mãn: 13 sinh viên/buổi bảo vệ, tối đa 3 buổi bảo vệ)"
  }
]
export const infoUser = {
  "id": 39166,
  "user_login": "champttph28681",
  "user_code": "PH28681",
  "user_surname": "Phạm",
  "user_middlename": "Thị Thanh",
  "user_givenname": "Châm",
  "user_email": "champttph28681@fpt.edu.vn",
  "user_address": "Cổng Văn Hóa thôn Kế Thiện, xã Kế Thiện, huyện Bình Xuyên, tỉnh Vĩnh Phúc",
  "user_telephone": "0-0367972573",
  "curriculum_id": 204,
  "full_name": "Phạm Thị Thanh Châm",
  "campus_code": "ph",
  "chuyen_nganh": "Quản trị doanh nghiệp vừa và nhỏ(Marketing và Bán hàng)",
  "brand_code": "MA"
}

export const sms =[
  {
      "id": 154785,
      "phone": "0367972573",
      "owner_name": "",
      "owner_type": "Sinh viên",
      "student_code": "PH28681",
      "created_on": "28/09/2021 23:04",
      "is_active": 1
  },
  {
      "id": 154786,
      "phone": "0981938790",
      "owner_name": "",
      "owner_type": "Phụ huynh",
      "student_code": "PH28681",
      "created_on": "28/09/2021 23:04",
      "is_active": 1
  }
]
export const point = [
  {
    id: 1,
    subject_name: 'Kỹ năng làm việc',
    status:'Passed',
    point: [
      {
        title: 'Document',
        pointItem: 6,
        weight: 30
      },{
        title: 'Lab 1',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 2',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 3',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 4',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 5',
        pointItem: 6,
        weight: 10
      },
      {
        title: 'Lab 6',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 7',
        pointItem: 6,
        weight: 10
      },
    ]
  },
  {
    id: 2,
    subject_name: 'Khởi sự doanh nghiệp',
    status:'Passed',
    point: [
      {
        title: 'Document',
        pointItem: 6,
        weight: 30
      },{
        title: 'Lab 1',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 2',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 3',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 4',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 5',
        pointItem: 6,
        weight: 10
      },
      {
        title: 'Lab 6',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 7',
        pointItem: 6,
        weight: 10
      },
    ]
  },
  {
    id: 3,
    subject_name: 'Quản trị website',
    status:'Passed',
    point: [
      {
        title: 'Document',
        pointItem: 6,
        weight: 30
      },{
        title: 'Lab 1',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 2',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 3',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 4',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 5',
        pointItem: 6,
        weight: 10
      },
      {
        title: 'Lab 6',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 7',
        pointItem: 6,
        weight: 10
      },
    ]
  },
  {
    id: 4,
    subject_name: 'Front-end freamwork 2',
    status:'Passed',
    point: [
      {
        title: 'Document',
        pointItem: 6,
        weight: 30
      },{
        title: 'Lab 1',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 2',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 3',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 4',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 5',
        pointItem: 6,
        weight: 10
      },
      {
        title: 'Lab 6',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 7',
        pointItem: 6,
        weight: 10
      },
    ]
  },
  {
    id: 5,
    subject_name: 'Front-end freamwork 1',
    status:'Passed',
    point: [
      {
        title: 'Document',
        pointItem: 6,
        weight: 30
      },{
        title: 'Lab 1',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 2',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 3',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 4',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 5',
        pointItem: 6,
        weight: 10
      },
      {
        title: 'Lab 6',
        pointItem: 6,
        weight: 10
      },{
        title: 'Lab 7',
        pointItem: 6,
        weight: 10
      },
    ]
  },
]